language: node_js
node_js:
  - "node"
sudo: required
services:
  - docker
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t joshcummingsdesign/docker-test .
  - docker push joshcummingsdesign/docker-test
after_success:
  - git push staging master
