language: node_js
node_js:
  - "node"
sudo: required
services:
  - docker
before_install:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker build -t joshcummingsdesign/docker-test .
- docker push joshcummingsdesign/docker-test
