language: node_js
node_js:
  - "node"
sudo: required
services:
  - docker
before_install:
- docker build -t joshcummingsdesign/docker-test .
- docker run -d -p 80:80 joshcummingsdesign/docker-test
- docker ps -a
